### ISSUE TITLE
google-services.json is missing

### ISSUE THREAD

**Issue by katlehotech** [blockchain/My-Wallet-V3-Android#437]
Error:Execution failed for task ':app:processDevDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\Thapelo\Documents\My-Wallet-V3-Android-master\app\src\dev\debug\google-services.json
  C:\Users\Thapelo\Documents\My-Wallet-V3-Android-master\app\src\debug\dev\google-services.json
  C:\Users\Thapelo\Documents\My-Wallet-V3-Android-master\app\src\dev\google-services.json
  C:\Users\Thapelo\Documents\My-Wallet-V3-Android-master\app\src\debug\google-services.json
  C:\Users\Thapelo\Documents\My-Wallet-V3-Android-master\app\google-services.json

**Comment by ditn** [comment]
The app requires Firebase/Google services to run correctly, which are configured via the google-services.json file. We don't host that file on GitHub because it contains private keys.

You can either [generate and add your own Firebase config](https://firebase.google.com/docs/android/setup), or remove the `apply plugin: 'com.google.gms.google-services'` and `compile "com.google.firebase:firebase-messaging:$googleServicesVersion"` lines from build.gradle (which will break`FcmCallbackService.java` and `InstanceIdService.java`, but they're not critical right now).

**Comment by katlehotech** [comment]
I created the config file it's now working. Thank you
