### ISSUE TITLE
Internet explorer

### ISSUE THREAD

**Issue by sharity-app** [blockchain/My-Wallet-V3-Android#715]
when using a browser the apps asks for internet explorer on android ^^ !!! Can that be switched to chrome by default. I mean internent explorer does not even exist on goog play ... also the page redirects to a weird link that proposes other links to browsers...

**Comment by ditn** [comment]
Can you clarify what you mean here? Steps to recreate?

**Comment by sharity-app** [comment]
Say you click on get bitcoin current app ask for a browser... That browser
is internet explorer

Le 25 sept. 2017 1:26 PM, "Adam Bennett" <notifications@github.com> a
écrit :

**Comment by sharity-app** [comment]
It seems to be called in android.data.api

Connection api

Le 25 sept. 2017 1:32 PM, "Jérôme Sinpaseuth" <jerome@sharity-app.co> a
écrit :

**Comment by ditn** [comment]
Android version? Device make/model? Screenshots if possible please.

**Comment by sharity-app** [comment]
It's a Huawei p9, running on nougat...
And it does not allow me to take a screenshot ^^

Le 25 sept. 2017 1:36 PM, "Adam Bennett" <notifications@github.com> a
écrit :

**Comment by ditn** [comment]
Settings -> Enable Screenshots

**Comment by sharity-app** [comment]
Le 25 sept. 2017 1:42 PM, "Adam Bennett" <notifications@github.com> a
écrit :

**Comment by sharity-app** [comment]
And also it get you to there



Le 25 sept. 2017 1:45 PM, "Jérôme Sinpaseuth" <jerome@sharity-app.co> a
écrit :

**Comment by ditn** [comment]
I don't think you can send images via email replies! Not seeing anything on GitHub.

**Comment by sharity-app** [comment]
managed. first screen is where you get redirect to second is the error message

**Comment by sharity-app** [comment]
My-Wallet-V3-Android/app/src/main/java/piuk/blockchain/android/data/api/ConnectionApi.kt

**Comment by sharity-app** [comment]
In mean it seems to be in the response body from YOUR SERVER

**Comment by sharity-app** [comment]
interface ConnectionEndpoint {

    @GET(".")
    fun pingExplorer(): Observable<ResponseBody>

}

**Comment by sharity-app** [comment]
and i also get that on the official google play android app for some reason

**Comment by ditn** [comment]
It's nothing to do with our server or the endpoint you mentioned.

So, as you can see [here](https://github.com/blockchain/My-Wallet-V3-Frontend/blob/41ca8fcb393079ad3a9d08fe6b93a9441b5f296c/assets/js/wallet-app.module.js#L9) we redirect users who have an out-of-date version of IE to the browsehappy site, which explains your first screenshot.

Obviously you're _not_ running IE, but it's possible that your phone is mis-reporting it's user agent to the window, either because Huawei have done something weird or some component of your phone is very out of date.

Make sure that your version of the Chrome browser is 45 or above as the wallet isn't supported on anything lower and V61 is out currently.

Also check that your [webview client is up to date](https://play.google.com/store/apps/details?id=com.google.android.webview); I think it's more likely that this is the root cause of the problem you're seeing, if the issue isn't with Huawei's Android implementation.

**Comment by sharity-app** [comment]
yeah it's a bit weird.. but everything does makes sense not thanks. i'll try to fix this

**Comment by ditn** [comment]
Let me know if you manage to resolve the issue, we're looking at it closely on our end too just in case.

**Comment by sharity-app** [comment]
nah my chrome is 61 so not the issue most is up to date. Might be the browser detection function used..
